version: "3"

services:
  lebedev-flask:
    build:
      context: ..
      dockerfile: docker/Dockerfile-tgserver
    restart: unless-stopped
    volumes:
      - "/srv/lebedev/cache:/home/lebedev/cache"
    ports:
      - "9898:9898"
  lebedev-tgclient:
    build:
      context: ..
      dockerfile: docker/Dockerfile-tgclient
    restart: unless-stopped
    depends_on:
      - lebedev-flask
  